// src/dd/cursorrules.mjs
/**
 * Generate .cursorrules file from project context
 */

/**
 * Generate .cursorrules content from project configuration
 * @param {object} project - Project configuration from API
 * @returns {string} - Content for .cursorrules file
 */
export function generateCursorRules(project) {
  const sections = [];

  // Header
  sections.push(`# Cursor Rules for ${project.project_name || 'Project'}`);
  sections.push(`# Generated by dawson-does-framework pull`);
  sections.push(`# Template: ${project.template}`);
  sections.push('');

  // Project Context
  sections.push('## Project Context');
  sections.push('');

  if (project.vision) {
    sections.push('### Vision');
    sections.push(project.vision);
    sections.push('');
  }

  if (project.mission) {
    sections.push('### Mission');
    sections.push(project.mission);
    sections.push('');
  }

  if (project.description) {
    sections.push('### Description');
    sections.push(project.description);
    sections.push('');
  }

  if (project.success_criteria) {
    sections.push('### Success Criteria');
    sections.push(project.success_criteria);
    sections.push('');
  }

  // Tech Stack based on template and integrations
  sections.push('## Tech Stack');
  sections.push('');

  const techStack = buildTechStack(project.template, project.integrations || {});
  for (const [category, tech] of Object.entries(techStack)) {
    if (tech) {
      sections.push(`- **${category}**: ${tech}`);
    }
  }
  sections.push('');

  // Development Guidelines
  sections.push('## Development Guidelines');
  sections.push('');
  sections.push('### Code Style');
  sections.push('- Use TypeScript for type safety');
  sections.push('- Follow the existing code patterns in the codebase');
  sections.push('- Use descriptive variable and function names');
  sections.push('- Add comments for complex logic');
  sections.push('');

  sections.push('### File Organization');
  sections.push('- Components in `app/components/` or `components/`');
  sections.push('- Utilities in `lib/` or `utils/`');
  sections.push('- API routes in `app/api/`');
  sections.push('- Types in `types/` or colocated with components');
  sections.push('');

  // Integration-specific rules
  if (project.integrations) {
    const integrationRules = generateIntegrationRules(project.integrations);
    if (integrationRules.length > 0) {
      sections.push('### Integration Guidelines');
      sections.push('');
      for (const rule of integrationRules) {
        sections.push(`- ${rule}`);
      }
      sections.push('');
    }
  }

  // Inspirations reference
  if (project.inspirations && project.inspirations.length > 0) {
    sections.push('## Reference Inspirations');
    sections.push('');
    for (const insp of project.inspirations) {
      sections.push(`- [${insp.type}] ${insp.value}`);
    }
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Build tech stack description from template and integrations
 */
function buildTechStack(template, integrations) {
  const stack = {
    Framework: 'Next.js 14+ (App Router)',
    Language: 'TypeScript',
    Styling: 'Tailwind CSS',
  };

  // Add integration-specific tech
  if (integrations.auth === 'supabase') {
    stack.Auth = 'Supabase Auth';
    stack.Database = 'Supabase (PostgreSQL)';
  } else if (integrations.auth === 'clerk') {
    stack.Auth = 'Clerk';
  } else if (integrations.auth === 'nextauth') {
    stack.Auth = 'NextAuth.js';
  }

  if (integrations.payments === 'stripe') {
    stack.Payments = 'Stripe';
  } else if (integrations.payments === 'lemon-squeezy') {
    stack.Payments = 'Lemon Squeezy';
  } else if (integrations.payments === 'paddle') {
    stack.Payments = 'Paddle';
  }

  if (integrations.email === 'resend') {
    stack.Email = 'Resend';
  } else if (integrations.email === 'sendgrid') {
    stack.Email = 'SendGrid';
  } else if (integrations.email === 'postmark') {
    stack.Email = 'Postmark';
  }

  if (integrations.ai === 'openai') {
    stack.AI = 'OpenAI';
  } else if (integrations.ai === 'anthropic') {
    stack.AI = 'Anthropic Claude';
  }

  if (integrations.analytics === 'posthog') {
    stack.Analytics = 'PostHog';
  } else if (integrations.analytics === 'plausible') {
    stack.Analytics = 'Plausible';
  } else if (integrations.analytics === 'mixpanel') {
    stack.Analytics = 'Mixpanel';
  }

  if (integrations.storage === 'supabase') {
    stack.Storage = 'Supabase Storage';
  } else if (integrations.storage === 'cloudflare') {
    stack.Storage = 'Cloudflare R2';
  } else if (integrations.storage === 's3') {
    stack.Storage = 'AWS S3';
  }

  // Template-specific additions
  if (template === 'saas') {
    stack.Type = 'SaaS Application';
  } else if (template === 'seo-directory') {
    stack.Type = 'SEO Directory / Content Site';
  }

  return stack;
}

/**
 * Generate integration-specific development rules
 */
function generateIntegrationRules(integrations) {
  const rules = [];

  if (integrations.auth === 'supabase') {
    rules.push('Use Supabase client from `lib/supabase.ts` for all database operations');
    rules.push('Protect routes using middleware or server-side auth checks');
  } else if (integrations.auth === 'clerk') {
    rules.push('Use Clerk components and hooks for authentication UI');
    rules.push('Use `auth()` helper in Server Components for user info');
  }

  if (integrations.payments === 'stripe') {
    rules.push('Use Stripe webhooks for payment events, never trust client-side data');
    rules.push('Store subscription status in database, sync via webhooks');
  }

  if (integrations.email) {
    rules.push('Use email templates for consistent branding');
    rules.push('Queue emails for better reliability in production');
  }

  if (integrations.ai) {
    rules.push('Stream AI responses for better UX on long completions');
    rules.push('Implement rate limiting for AI endpoints');
  }

  return rules;
}

/**
 * Generate START_PROMPT.md content tailored to the project
 */
export function generateStartPrompt(project) {
  const sections = [];

  sections.push(`# Start Prompt: ${project.project_name || 'Project'}`);
  sections.push('');
  sections.push('> Copy this prompt into Cursor Chat to get started with AI-assisted development.');
  sections.push('');
  sections.push('---');
  sections.push('');

  sections.push('## Project Overview');
  sections.push('');
  
  if (project.description) {
    sections.push(project.description);
    sections.push('');
  } else if (project.vision) {
    sections.push(project.vision);
    sections.push('');
  }

  sections.push(`**Template:** ${project.template}`);
  sections.push('');

  // List integrations
  if (project.integrations) {
    const activeIntegrations = Object.entries(project.integrations)
      .filter(([, v]) => v)
      .map(([k, v]) => `${k}: ${v}`);
    
    if (activeIntegrations.length > 0) {
      sections.push('**Integrations:**');
      for (const int of activeIntegrations) {
        sections.push(`- ${int}`);
      }
      sections.push('');
    }
  }

  sections.push('## Getting Started');
  sections.push('');
  sections.push('I\'m starting a new project. Here\'s the context:');
  sections.push('');
  
  if (project.vision) {
    sections.push(`**Vision:** ${project.vision}`);
    sections.push('');
  }
  
  if (project.mission) {
    sections.push(`**Mission:** ${project.mission}`);
    sections.push('');
  }
  
  if (project.success_criteria) {
    sections.push(`**Success Criteria:** ${project.success_criteria}`);
    sections.push('');
  }

  sections.push('Please help me:');
  sections.push('1. Review the current project structure');
  sections.push('2. Identify what needs to be configured (env vars, API keys, etc.)');
  sections.push('3. Suggest first steps to make this project functional');
  sections.push('');

  if (project.inspirations && project.inspirations.length > 0) {
    sections.push('## Reference Inspirations');
    sections.push('');
    sections.push('These are some inspirations for the project:');
    for (const insp of project.inspirations) {
      sections.push(`- [${insp.type}] ${insp.value}`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push('');
  sections.push('*Generated by `framework pull` - see `.cursorrules` for AI context*');

  return sections.join('\n');
}

