import JSZip from "jszip";
import { saveAs } from "file-saver";
import { getRequiredEnvVars } from "./command-builder";
import { TEMPLATES, INTEGRATION_INFO } from "./templates";

interface ZipConfig {
  template: string;
  projectName: string;
  integrations: Record<string, string>;
  vision?: string;
  mission?: string;
  successCriteria?: string;
  envKeys?: Record<string, string>;
}

/**
 * Generate project files and download as ZIP
 * Note: This creates a starter structure - for full templates, use the CLI command
 */
export async function generateProjectZip(config: ZipConfig): Promise<void> {
  const zip = new JSZip();
  const {
    template,
    projectName,
    integrations,
    vision,
    mission,
    successCriteria,
    envKeys,
  } = config;

  const templateInfo = TEMPLATES[template as keyof typeof TEMPLATES];
  const requiredEnvVars = getRequiredEnvVars(integrations);

  // Create .dd/ directory with framework metadata
  const ddFolder = zip.folder(".dd")!;

  // template-manifest.json
  ddFolder.file(
    "template-manifest.json",
    JSON.stringify(
      {
        template,
        templateName: templateInfo?.name || template,
        version: "1.0.0",
        generatedAt: new Date().toISOString(),
        generatedBy: "dawson-does-framework-configurator",
        integrations: Object.entries(integrations)
          .filter(([, v]) => v)
          .reduce((acc, [k, v]) => ({ ...acc, [k]: v }), {}),
      },
      null,
      2
    )
  );

  // Vision document
  if (vision?.trim()) {
    ddFolder.file(
      "vision.md",
      `# Project Vision\n\n${vision.trim()}\n\n---\n*Generated by dawson-does-framework configurator*\n`
    );
  }

  // Mission document
  if (mission?.trim()) {
    ddFolder.file(
      "mission.md",
      `# Project Mission\n\n${mission.trim()}\n\n---\n*Generated by dawson-does-framework configurator*\n`
    );
  }

  // Goals document
  if (successCriteria?.trim()) {
    ddFolder.file(
      "goals.md",
      `# Success Criteria\n\n${successCriteria.trim()}\n\n---\n*Generated by dawson-does-framework configurator*\n`
    );
  }

  // Create .env.local.example
  if (requiredEnvVars.length > 0) {
    const envContent = [
      "# Environment Variables",
      "# Copy this file to .env.local and fill in your values",
      "#",
      `# Generated for: ${templateInfo?.name || template} template`,
      `# Integrations: ${Object.entries(integrations)
        .filter(([, v]) => v)
        .map(([k, v]) => `${k}:${v}`)
        .join(", ")}`,
      "",
      ...requiredEnvVars.map((varName) => {
        const value = envKeys?.[varName] || "your_value_here";
        return `${varName}=${value}`;
      }),
      "",
    ].join("\n");

    zip.file(".env.local.example", envContent);
  }

  // Create package.json with correct dependencies
  const dependencies: Record<string, string> = {
    next: "^15.0.0",
    react: "^19.0.0",
    "react-dom": "^19.0.0",
  };

  const devDependencies: Record<string, string> = {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    typescript: "^5.0.0",
    tailwindcss: "^3.4.0",
    postcss: "^8.0.0",
    autoprefixer: "^10.0.0",
  };

  // Add integration dependencies
  const integrationDeps = getIntegrationDependencies(integrations);
  Object.assign(dependencies, integrationDeps);

  const packageJson = {
    name: projectName || "my-project",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies,
    devDependencies,
  };

  zip.file("package.json", JSON.stringify(packageJson, null, 2) + "\n");

  // Create README.md
  const readme = generateReadme(config, requiredEnvVars);
  zip.file("README.md", readme);

  // Create basic Next.js app structure
  const appFolder = zip.folder("app")!;
  
  // layout.tsx
  appFolder.file(
    "layout.tsx",
    `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated with dawson-does-framework',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
  );

  // page.tsx
  appFolder.file(
    "page.tsx",
    `export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gray-900 text-white">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">${projectName}</h1>
        <p className="text-gray-400 mb-8">
          Generated with dawson-does-framework
        </p>
        <div className="bg-gray-800 p-6 rounded-lg text-left max-w-md mx-auto">
          <h2 className="text-xl font-semibold mb-4 text-green-400">Next Steps:</h2>
          <ol className="space-y-2 text-sm text-gray-300">
            <li>1. Run <code className="text-green-400">npm install</code></li>
            <li>2. Copy <code className="text-green-400">.env.local.example</code> to <code className="text-green-400">.env.local</code></li>
            <li>3. Fill in your API keys</li>
            <li>4. Run <code className="text-green-400">npm run dev</code></li>
          </ol>
        </div>
        <p className="mt-8 text-xs text-gray-500">
          For full templates with pre-built components, use the CLI command instead.
        </p>
      </div>
    </main>
  )
}
`
  );

  // globals.css
  appFolder.file(
    "globals.css",
    `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-start-rgb: 17, 24, 39;
  --background-end-rgb: 17, 24, 39;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`
  );

  // tailwind.config.ts
  zip.file(
    "tailwind.config.ts",
    `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`
  );

  // postcss.config.js
  zip.file(
    "postcss.config.js",
    `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
  );

  // tsconfig.json
  zip.file(
    "tsconfig.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2
    ) + "\n"
  );

  // .gitignore
  zip.file(
    ".gitignore",
    `# Dependencies
node_modules
.pnpm-debug.log*

# Next.js
.next/
out/

# Production
build

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env*.local
.env

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts
`
  );

  // next.config.js
  zip.file(
    "next.config.js",
    `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`
  );

  // Generate and download ZIP
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${projectName || "project"}.zip`);
}

function getIntegrationDependencies(
  integrations: Record<string, string>
): Record<string, string> {
  const deps: Record<string, string> = {};

  Object.entries(integrations).forEach(([type, provider]) => {
    if (!provider) return;

    switch (`${type}:${provider}`) {
      case "auth:supabase":
      case "db:supabase":
        deps["@supabase/supabase-js"] = "^2.47.10";
        deps["@supabase/ssr"] = "^0.1.0";
        break;
      case "auth:clerk":
        deps["@clerk/nextjs"] = "^5.0.0";
        break;
      case "payments:stripe":
        deps["stripe"] = "^14.21.0";
        break;
      case "payments:paddle":
        deps["@paddle/paddle-js"] = "^1.0.0";
        break;
      case "email:resend":
        deps["resend"] = "^3.2.0";
        deps["react-email"] = "^2.1.0";
        deps["@react-email/components"] = "^0.0.15";
        break;
      case "email:sendgrid":
        deps["@sendgrid/mail"] = "^8.0.0";
        break;
      case "ai:openai":
        deps["openai"] = "^4.28.0";
        deps["ai"] = "^3.0.0";
        break;
      case "ai:anthropic":
        deps["@anthropic-ai/sdk"] = "^0.32.1";
        break;
      case "analytics:posthog":
        deps["posthog-js"] = "^1.100.0";
        break;
      case "analytics:plausible":
        deps["next-plausible"] = "^3.12.0";
        break;
    }
  });

  return deps;
}

function generateReadme(
  config: ZipConfig,
  requiredEnvVars: string[]
): string {
  const { template, projectName, integrations } = config;
  const templateInfo = TEMPLATES[template as keyof typeof TEMPLATES];

  const integrationsDesc = Object.entries(integrations)
    .filter(([, v]) => v)
    .map(([type, provider]) => `- **${type}**: ${provider}`)
    .join("\n");

  return `# ${projectName}

Generated with [dawson-does-framework](https://github.com/jrdaws/dawson-does-framework)

## Template

**${templateInfo?.name || template}** - ${templateInfo?.description || ""}

## Integrations

${integrationsDesc || "No integrations selected"}

## Getting Started

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Set up environment variables:**
   \`\`\`bash
   cp .env.local.example .env.local
   \`\`\`
   Then edit \`.env.local\` and add your API keys.

3. **Run the development server:**
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open [http://localhost:3000](http://localhost:3000) in your browser.

${
  requiredEnvVars.length > 0
    ? `## Environment Variables

The following environment variables are required:

${requiredEnvVars.map((v) => `- \`${v}\``).join("\n")}

Refer to each service's documentation for obtaining these values.
`
    : ""
}

## Full Template

This ZIP contains a starter structure. For the full template with pre-built components, 
authentication flows, and production-ready code, use the CLI command:

\`\`\`bash
npx @jrdaws/framework export ${template} ./${projectName}
\`\`\`

## Learn More

- [Framework Documentation](https://github.com/jrdaws/dawson-does-framework)
- [Next.js Documentation](https://nextjs.org/docs)

---

Generated on ${new Date().toLocaleDateString()}
`;
}

