/**
 * POST /api/projects/create
 * Create a new user-owned project for the My Projects dashboard
 * 
 * Requires authentication via Supabase Auth
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import type { CreateUserProjectInput, UserProject } from "@/lib/supabase";

export async function POST(request: NextRequest) {
  try {
    // Get auth token from header
    const authHeader = request.headers.get("authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return NextResponse.json(
        { error: "UNAUTHORIZED", message: "Missing or invalid authorization header" },
        { status: 401 }
      );
    }
    const accessToken = authHeader.substring(7);

    // Initialize Supabase client with user's token
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseAnonKey) {
      return NextResponse.json(
        { error: "CONFIG_ERROR", message: "Supabase not configured" },
        { status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: `Bearer ${accessToken}` } },
    });

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: "UNAUTHORIZED", message: "Invalid or expired token" },
        { status: 401 }
      );
    }

    // Parse request body
    const body: CreateUserProjectInput = await request.json();

    // Validate required fields
    if (!body.name?.trim()) {
      return NextResponse.json(
        { error: "VALIDATION_ERROR", message: "Project name is required" },
        { status: 400 }
      );
    }

    // Create project - slug and npx_token are auto-generated by DB triggers
    const { data: project, error: insertError } = await supabase
      .from("user_projects")
      .insert({
        user_id: user.id,
        name: body.name.trim(),
        description: body.description?.trim() || null,
        template: body.template || null,
        features: body.features || [],
        integrations: body.integrations || {},
      })
      .select()
      .single();

    if (insertError) {
      console.error("[Projects Create] Insert error:", insertError);
      return NextResponse.json(
        { error: "DATABASE_ERROR", message: insertError.message },
        { status: 500 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        project: project as UserProject,
      },
      { status: 201 }
    );
  } catch (error: unknown) {
    console.error("[Projects Create] Error:", error);
    return NextResponse.json(
      { error: "INTERNAL_ERROR", message: "Failed to create project" },
      { status: 500 }
    );
  }
}

